### ISSUE TITLE
When forking an application and copying pg data: `SyntaxError: Unexpected token <`

### ISSUE THREAD

**Issue by Taytay** [heroku/heroku-fork#2]
I ran: `heroku fork --copy-pg-data --app base-app-name target-app-name`

```
Adding addon sendgrid:starter to target-app-name... done
Adding addon heroku-postgresql:standard-0 to target-app-name... done
Transferring HEROKU_POSTGRESQL_BROWN to HEROKU_POSTGRESQL_ORANGE...
SyntaxError: Unexpected token <
    at Object.parse (native)
    at Request.parseBody (/Users/taylorbrown/.heroku/node_modules/heroku-fork/node_modules/heroku-client/lib/request.js:230:17)
    at Request.handleFailure (/Users/taylorbrown/.heroku/node_modules/heroku-fork/node_modules/heroku-client/lib/request.js:261:19)
    at ConcatStream.directResponse [as cb] (/Users/taylorbrown/.heroku/node_modules/heroku-fork/node_modules/heroku-client/lib/request.js:167:12)
    at ConcatStream.end (/Users/taylorbrown/.heroku/node_modules/heroku-fork/node_modules/heroku-client/node_modules/concat-stream/index.js:44:21)
    at IncomingMessage.onend (_stream_readable.js:489:10)
    at IncomingMessage.g (events.js:257:16)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:163:7)
    at _stream_readable.js:891:16
```

I echoed the buffer to see what it was trying to convert into an object, and got this:
`about to parse buffer <Buffer 3c 68 31 3e 4e 6f 74 20 46 6f 75 6e 64 3c 2f 68 31 3e>`

I haven't translated this into ascii yet.

**Comment by Taytay** [comment]
Heh - that buffer is: `<h1>Not Found</h1>`

**Comment by Taytay** [comment]
And this is the request that failed:

```
{ domain: null,
  _events:
   { response: { [Function: g] listener: [Function] },
     socket: { [Function: g] listener: [Function] } },
  _eventsCount: 2,
  _maxListeners: undefined,
  output: [],
  outputEncodings: [],
  outputCallbacks: [],
  writable: true,
  _last: false,
  chunkedEncoding: false,
  shouldKeepAlive: true,
  useChunkedEncodingByDefault: true,
  sendDate: false,
  _removedHeader: {},
  _contentLength: null,
  _hasBody: true,
  _trailer: '',
  finished: false,
  _hangupClose: false,
  _headerSent: false,
  socket: null,
  connection: null,
  _header: null,
  _headers:
   { accept: 'application/vnd.heroku+json; version=3',
     'content-type': 'application/json',
     range: 'id ]..; max=1000',
     host: 'postgres-starter-api.heroku.com',
     authorization: 'Basic OmRlOTRlNmVhLTNiNzMtNDE5ZC04MDkyLWYyZjQxNGFkYmEzMA==' },
  _headerNames:
   { accept: 'Accept',
     'content-type': 'Content-type',
     range: 'Range',
     host: 'Host',
     authorization: 'Authorization' },
  agent:
   { domain: null,
     _events: { free: [Function] },
     _eventsCount: 1,
     _maxListeners: undefined,
     defaultPort: 443,
     protocol: 'https:',
     options: { maxSockets: 5000, path: null },
     requests: {},
     sockets: { 'postgres-starter-api.heroku.com:443::::::::': [Object] },
     freeSockets: {},
     keepAliveMsecs: 1000,
     keepAlive: false,
     maxSockets: 5000,
     maxFreeSockets: 256 },
  socketPath: undefined,
  method: 'POST',
  path: '/client/v11/databases/resting-deftly-8967/transfers' }
```

**Comment by Taytay** [comment]
And this is our database plan: `heroku-postgresql:standard-0  HEROKU_POSTGRESQL_BROWN`

**Comment by jdx** [comment]
#3 will fix this
